### ISSUE TITLE
Update 3.1.7 Code

### ISSUE THREAD

**Issue by jefftgraves** [mike-ward/tweet-gadget#1]
Mike - can you update this repo to the last 3.1.7 release so I can submit a pull request? I have two fixes: one to support Twitter's 280 characters and a new app key and secret as it looks like the existing one expired.

**Comment by mike-ward** [comment]
I'll have a look this weekend. Thanks...

**Comment by mike-ward** [comment]
OK, the archive should be current. Thanks!

**Comment by mike-ward** [comment]
@jefftgraves I've published a release. Can you have a look and see if it works? I don't have any Win 7 machines here.

https://github.com/mike-ward/tweet-gadget/releases/latest

**Comment by mike-ward** [comment]
Never mind, I found the Windows 10 thingy.

**Comment by jefftgraves** [comment]
Mike - 1 issue with the .gadget file. It's missing jquery.glob.js

**Comment by mike-ward** [comment]
Updated, thanks...
